version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          command: |
            docker login -u megop -p "$DOCKER_HUB_PASSWORD"
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag udagram-api-feed megop/udagram-api-feed:v3
            docker push megop/udagram-api-feed:v3
            docker tag udagram-api-user megop/udagram-api-user:v3
            docker push megop/udagram-api-user:v3
            docker tag udagram-frontend megop/udagram-frontend:v3
            docker push megop/udagram-frontend:v3
            docker tag udagram-reverseproxy megop/udagram-reverseproxy:v3
            docker push megop/udagram-reverseproxy:v3

workflows:
  udagram:
    jobs:
      - build
